### ISSUE TITLE
can't install example

### ISSUE THREAD

**Issue by todzhang** [reeflective/console#11]
go install github.com/reeflective/console/example

# github.com/reeflective/console
/home/tester/go/pkg/mod/github.com/reeflective/console@v0.0.0-20230120113638-77a4695d6f8a/tab-completer.go:34:27: undefined: carapace.Complete

**Comment by maxlandon** [comment]
Hello,

My install instructions are wrong: I forgot that the classic `go install` command does not work when there are replace directives in the go.mod. These directives should go away in the near future.

In the meantime, this will work:
```bash
git clone https://github.com/reeflective/console
cd console/example
go install
```
Then
```
example
```
will drop you the console app.

**Comment by maxlandon** [comment]
For anyone reading this, please know that a simple `go install github.com/reeflective/console/example` is now working for installing the example application.

All previous go `replace` directives that were forbidding this have been removed.
