### ISSUE TITLE
Failed to use import the module and run it locally

### ISSUE THREAD

**Issue by 3santree** [reeflective/console#32]
```
haha@ubuntu:~/Documents/testconsole$ tree
.
├── go.mod
├── go.sum
└── main.go

0 directories, 3 files
haha@ubuntu:~/Documents/testconsole$ cat main.go
package main

import (
        "github.com/reeflective/console"
)

func main() {
        app := console.New("start")
        app.Start()
}
haha@ubuntu:~/Documents/testconsole$ go run .
# github.com/reeflective/console
../../go/pkg/mod/github.com/reeflective/console@v0.1.10/completer.go:32:27: undefined: carapace.Complete
h
```
Run the console/example without no problem. But when I tried to test the code outside the console folder, it failed with the same message. Then I tried with minimal `app.Start()` provides the same error message.
What should I do to make my code run using the console library?

**Comment by maxlandon** [comment]
Hello,

Can you please show me your go.mod content ?

So currently there is a `replace` directive because the completion engine is a patched fork.

I thought that no replace directive would be needed on the consumer side, but I may be wrong, in which case I'm glad you raised this issue.

**Comment by maxlandon** [comment]
In a first time, try adding the following to your go mod (replacing (version-or-tag) with the current tag  of the carapace indirect dependency):

`replace github.com/rsteube/carapace (version-or-tag) > github.com/reeflective/carapace library`

Once done, do
`go mod tidy && go build`

It should fetch the patched completer library and compile correctly.

**Comment by 3santree** [comment]
```
    1  module testconsole
    2                                           
    3  go 1.21.1                                                                                   
    4
    5  require github.com/reeflective/console v0.1.10
    6
    7  require (
    8      github.com/inconshreveable/mousetrap v1.1.0 // indirect
    9      github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51 // indirect
   10      github.com/kr/text v0.2.0 // indirect
   11      github.com/reeflective/readline v1.0.9 // indirect
   12      github.com/rivo/uniseg v0.4.4 // indirect
   13      github.com/rogpeppe/go-internal v1.11.0 // indirect
   14      github.com/rsteube/carapace v0.43.3 // indirect
   15      github.com/rsteube/carapace-shlex v0.0.4 // indirect
   16      github.com/spf13/cobra v1.7.0 // indirect
   17      github.com/spf13/pflag v1.0.5 // indirect
   18      golang.org/x/exp v0.0.0-20220909182711-5c715a9e8561 // indirect
   19      golang.org/x/sys v0.8.0 // indirect
   20      golang.org/x/term v0.8.0 // indirect
   21      gopkg.in/yaml.v3 v3.0.1 // indirect
   22  )
   23
+  24  replace github.com/rsteube/carapace v0.43.3 => github.com/reeflective/carapace library
 ```
Hi, thanks for the instruction. I've added the line 24 and run the commands as you suggested, the program can run now!

**Comment by maxlandon** [comment]
Yup okay this works.

Thanks for pointing it out.

For anyone stumbling on this issue, the problem should be resolved in the future, when the patched fork is not needed any longer.

Pinning it as it's very likely someone will face this problem again in the meantime.

**Comment by 3santree** [comment]
Update: I replaced the `library` word with its `version` tag.
The following works but will have syntax error in go.mod:
```
replace github.com/rsteube/carapace v0.43.3 => github.com/reeflective/carapace library
```
Now the following works and won't have syntax error:
```
replace github.com/rsteube/carapace v0.43.3 => github.com/reeflective/carapace v0.25.1
```
To find the version, go to the github page of the code and you will find all versions in `tags`

Thanks for the reply.

**Comment by maxlandon** [comment]
The point of using the library "tag" (sorry, I've mislead you: it's the library branch) is that when you `go mod tidy`, the go toolchain will automatically resolve to the library branch's HEAD.

Therefore you should not specify the version number yourself, just put library and go mod tidy.

Your current v0.25.1 also does not include the latest code.

**Comment by 3santree** [comment]
Oh thanks for the explain, didn't know it before!

**Comment by maxlandon** [comment]
For anyone reading this, please know that a simple `go install github.com/reeflective/console/example` is now working for installing the example application.

All previous go `replace` directives that were forbidding this have been removed.
