### ISSUE TITLE
Console incompatible with bubbletea progress bar.

### ISSUE THREAD

**Issue by moqsien** [reeflective/console#41]
[bubbletea progress bar](https://github.com/charmbracelet/bubbletea/tree/master/examples/progress-download)

When using console with bubbletea progress bar, a new prompt line will display incorrectly, and cannot read input lines.

![error_console](https://github.com/reeflective/console/assets/34511192/9fce90ef-a7ee-434c-8495-0b6fd4a68b16)

**Comment by maxlandon** [comment]
@moqsien can you give a code snippet please ?

By the way I would strongly advise you to use this progress bar instead: https://github.com/cheggaaa/pb
Much simpler and no bugs.

**Comment by maxlandon** [comment]
I added the code of the bubbletea example in the `download` command code (using the [example app](https://github.com/reeflective/console/example)), everything works on my side, input still works fine.

(The rest of the code in `tui.go` file of the bubbletea example is not included here for conciseness).

```go
		downloadCmd := &cobra.Command{
			Use:     "download [flags] URL DESTINATION",
			Short:   "Download a file from a URL",
			GroupID: "filesystem",
			Args:    cobra.ExactArgs(2),
			Run: func(cmd *cobra.Command, args []string) {
				url := args[0]
				destination := args[1]

				fmt.Printf("Downloading file from URL: %s to destination: %s\n", url, destination)

				// Implementation logic for download command
				resp, err := getResponse(url)
				if err != nil {
					fmt.Println("could not get response", err)
					return
				}
				defer resp.Body.Close() // nolint:errcheck

				// Don't add TUI if the header doesn't include content size
				// it's impossible see progress without total
				if resp.ContentLength <= 0 {
					fmt.Println("can't parse content length, aborting download")
					return
				}

				filename := filepath.Base(url)
				file, err := os.Create(filename)
				if err != nil {
					fmt.Println("could not create file:", err)
					os.Exit(1)
				}
				defer file.Close() // nolint:errcheck

				pw := &progressWriter{
					total:  int(resp.ContentLength),
					file:   file,
					reader: resp.Body,
					onProgress: func(ratio float64) {
						p.Send(progressMsg(ratio))
					},
				}

				m := model{
					pw:       pw,
					progress: progress.New(progress.WithDefaultGradient()),
				}
				// Start Bubble Tea
				p = tea.NewProgram(m)

				// Start the download
				go pw.Start()

				if _, err := p.Run(); err != nil {
					fmt.Println("error running program:", err)
				}
			},
		}
```

**Comment by moqsien** [comment]
> @moqsien can you give a code snippet please ?
> 
> By the way I would strongly advise you to use this progress bar instead: https://github.com/cheggaaa/pb Much simpler and no bugs.

I fix this bug by adding a time.Sleep(i) after the progress bar.

Thanks for your suggestion.
