### ISSUE TITLE
 Support for executing system commands with `!` ?

### ISSUE THREAD

**Issue by M09Ic** [reeflective/console#57]
I found that in the [readline](https://github.com/reeflective/readline) , it's possible to execute system commands using `!` .

![image](https://github.com/user-attachments/assets/c9eb3c92-2736-4591-8b52-af82c3c02403) 

For example: ! whoami

Is it possible to implement similar functionality in the console?

**Comment by maxlandon** [comment]
Added in last release, in the `commands/` directory.
